version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: python run.py
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
